### ISSUE TITLE
Background drawable's bounds are overwritten in ViewPager

### ISSUE THREAD

**Issue by glodos** [dmytrodanylyk/circular-progress-button#38]
Hello,
First of all thanks for this great widget. I'd like to report an issue with state persistency. 
The problem occurs in ViewPager, when the button is in progress state. If I scroll a number of pages and go back, I end up with something like on the screenshot.

![b](https://cloud.githubusercontent.com/assets/2659001/3897766/6ff1f38e-2264-11e4-830d-854c2e55ae37.png)

After debugging, I have found that background drawable's bounds are overwritten in View's draw() method to fit the view's bounds. The draw operation is invoked when the page is about to show. If it's invoked after the animation, then the button will look like on the screenshot.

I didn't find any way to fix it so far so maybe you guys will be able to do to something with it. 

Cheers

**Comment by dmytrodanylyk** [comment]
This may be fixed in #60
