### ISSUE TITLE
Request: set state instead of progress, and also allow to set state without animation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dmytrodanylyk/circular-progress-button#48]
Currently, we need to set the progress bar value which is a bit weird for moving between states, so I think it's better to use the state enum instead.

also, I didn't succeed setting a state (for example, in order for it to not start as "idle", but as "progress") without seeing the morphing animation.

I've also didn't find out how to make the view morph from error to progress, as I wanted to set the text "try again" when there is an error.

Please add these features.

I've tried to add both of those features as such, but it didn't work for some reason:

	public enum State {
		PROGRESS(50), IDLE(0), COMPLETE(100), ERROR(-1);
		private final int mProgressToUse;

		private State(final int progressToUse) {
			this.mProgressToUse = progressToUse;
		}
	}

	public void setState(final State state) {
		setState(state, true);
	}

	public void setState(final State state, final boolean animate) {
		if (mState == state)
			return;
		if (!animate)
			mState = state;
		if (animate)
			setProgress(state.mProgressToUse);
		else {
			switch (state) {
			case COMPLETE:
				mCompleteStateListener.onAnimationEnd();
				break;
			case ERROR:
				mErrorStateListener.onAnimationEnd();
				break;
			case IDLE:
				mIdleStateListener.onAnimationEnd();
				break;
			case PROGRESS:
				mProgressStateListener.onAnimationEnd();
				break;
			}
		}
	}

	public State getState() {
		return this.mState;
	}

**Comment by AndroidDeveloperLB** [comment]
Why was this closed? was it fixed/enhanced?

**Comment by dmytrodanylyk** [comment]
Use `button.setProgress(value);` to change state.

Constants in `CircularProgressButton`

```java
public static final int IDLE_STATE_PROGRESS = 0;
public static final int ERROR_STATE_PROGRESS = -1;
public static final int SUCCESS_STATE_PROGRESS = 100;
public static final int INDETERMINATE_STATE_PROGRESS = 50;
```

**Comment by AndroidDeveloperLB** [comment]
@dmytrodanylyk What about the issues I've written?
Also, if you put the constants this way, can you please consider setting them all to have the same prefix (Example: "STATE_..." ) ? This way it would be easy to reach each of them.

**Comment by sdrygalski** [comment]
It's not fixed but it's closed, shame.
