### ISSUE TITLE
UI glitch on Nexus 10

### ISSUE THREAD

**Issue by hamen** [dmytrodanylyk/circular-progress-button#53]
Hi
I'm having a weird behavior on my Nexus10:
![Screenshot](https://dl.dropboxusercontent.com/u/23398786/CircularProgressButton_Nexux10.png)
Everything is fine basically on every other device: Nexus 5, Moto E, S3, a bunch of emulated devices (even an emulated Nexus10).

Here is the XML

```xml
    <com.dd.CircularProgressButton
                android:id="@+id/signin_fragment_button"
                android:layout_width="196dp"
                android:layout_height="64dp"
                android:layout_marginTop="16dp"
                android:textColor="@color/white"
                android:textSize="18sp"
                app:cpb_selectorIdle="@drawable/signin_button"
                app:cpb_textComplete="Success"
                app:cpb_textError="Error"
                app:cpb_textIdle="Sign In"/>
```
When I click the button, it stays blue, show a spinning progressbar in the middle, then stops and goes on with the app logic.
The button doesn't animate, doesn't go green on success.
Any idea? I'm kinda stuck here. Help, please.

**Comment by dmytrodanylyk** [comment]
This may be fixed in #60
