### ISSUE TITLE
app:cpb_colorIndicator="@color/cpb_grey"

### ISSUE THREAD

**Issue by tosslife** [dmytrodanylyk/circular-progress-button#61]
<com.dd.CircularProgressButton
        android:id="@+id/circularButton"
        android:layout_width="70dp"
        android:layout_height="70dp"
        android:layout_centerInParent="true"
        android:textColor="@color/white"
        android:textSize="16sp"
        android:visibility="invisible"
        app:cpb_colorIndicator="@color/cpb_green"
        app:cpb_colorProgress="@color/transparent"
        app:cpb_cornerRadius="70dp"
        app:cpb_iconComplete="@drawable/ic_action_accept"
        app:cpb_iconError="@drawable/ic_action_cancel"
        app:cpb_selectorIdle="@color/cpb_complete_state_selector"
        app:cpb_textIdle="@string/action_download" />

this  app:cpb_colorIndicator="@color/cpb_grey"

not change！

**Comment by dmytrodanylyk** [comment]
By default `app:cpb_colorIndicatorBackground="@color/cpb_grey"` 
So setting the same value for `app:cpb_colorIndicator="@color/cpb_grey"` makes your progress indicator invisible. That's doesn't make sense.
