### ISSUE TITLE
cpb_TextXXX not picked up

### ISSUE THREAD

**Issue by FranciscoEstevez** [dmytrodanylyk/circular-progress-button#70]
For some reason the xml definition for the tests are not being picked up by my application, I have to do it programmatically.

Sample code:

            <com.dd.CircularProgressButton
                android:id="@+id/my_btn"
                android:layout_width="60dp"
                android:layout_height="30dp"
                android:textColor="@android:color/white"
                android:textSize="10sp"
                app:cpb_cornerRadius="48dp"
                app:cpb_textComplete="Complete"
                app:cpb_textError="Error"
                app:cpb_textIdle="Do Stuff"/>

       @InjectView(R.id.my_btn)
        CircularProgressButton myButton;

        myButton.setIndeterminateProgressMode(true);
        myButton.setProgress(0);

**Comment by lancevalour** [comment]
You have to add the project as an Android library in your application if you are not using gradle to make xml work,

**Comment by FranciscoEstevez** [comment]
I am using gradle to import it.

**Comment by dmytrodanylyk** [comment]
You are not missing `xmlns:app="http://schemas.android.com/apk/res-auto"` ?

**Comment by FranciscoEstevez** [comment]
Found the problem, the example uses 'app' namespace. When Android Studio nags about lack of namespace and it suggests importing it, except that due to collision it imports "http://schemas.android.com/tools" instead.

Solved, thank you.

**Comment by FranciscoEstevez** [comment]
Now for some reason those fields do not pick up @string/XXX references, but that's another issue.

**Comment by FranciscoEstevez** [comment]
Not it doesn't pick reference felds or get autocompletion on AS; but I guess that's another problem.
