### ISSUE TITLE
Text on the button

### ISSUE THREAD

**Issue by davix10** [dmytrodanylyk/circular-progress-button#75]
Hi, why I don't see text on the button?

**Comment by dmytrodanylyk** [comment]
Provide code.

**Comment by davix10** [comment]
This is the code

<com.dd.CircularProgressButton
            android:id="@+id/btnWithText"
            android:layout_width="196dp"
            android:layout_height="64dp"
            android:layout_marginTop="16dp"
            android:textColor="@color/white"
            android:textSize="18sp"
            app:cpb_textComplete="@string/Complete"
            app:cpb_textError="@string/Error"
            app:cpb_textIdle="@string/Upload" />

I see the button without written

**Comment by dmytrodanylyk** [comment]
Try to Can you install sample app from [play store](https://play.google.com/store/apps/details?id=com.dd.sample.processbutton&hl=en)?

**Comment by davix10** [comment]
The app works and I see correctly written

**Comment by dmytrodanylyk** [comment]
Means you are making something wrong, check out [sample app source code](https://github.com/dmytrodanylyk/circular-progress-button/tree/master/sample)

**Comment by davix10** [comment]
I tried but it does not work the same, I copied the code but it does not work the same.

**Comment by davix10** [comment]
Please help me!

**Comment by dmytrodanylyk** [comment]
Have you added `xmlns:app="http://schemas.android.com/apk/res-auto` to your root view?

**Comment by davix10** [comment]
Thanks a lot!!! now works!
