### ISSUE TITLE
Animation issues when using Proguard

### ISSUE THREAD

**Issue by SabriApps** [dmytrodanylyk/circular-progress-button#79]
Circle progress isn't animating, just shows a solid border to the circle.
I tried adding this code to 'proguard-rules.pro', but didn't make a difference.

`-keep class com.github.dmytrodanylyk.circular-progress-button.** { *; }` 
`-keep interface com.github.dmytrodanylyk.circular-progress-button.** { *; }`

**Comment by iceberg1369** [comment]
I have also come across this problem, anybody any idea to solve it?

**Comment by dmytrodanylyk** [comment]
Hi, sorry for long reply. Add following lines to your `proguard-rules.txt` file.

```
-keep class com.dd.** { *; }
-dontwarn com.dd.**
```
